### ISSUE TITLE
Clarify the rules about which paths are fixed and TileMatrixSet IDs

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-tiles#101]
- `{tileMatrixSetId}` is currently an optional variable (permission)
- The TileMatrixSet IDs is optional -- should _OGC API - Tiles_ make it required?
- Clients have no ways of knowing valid values for the `{tileMatrixSetId}`, as IDs are not even required, so the [API approach](https://github.com/opengeospatial/ogcapi-tiles/tree/master/QuickGuide#api-approach) is limited
- Even if ids were required, retrieving valid IDs would either require a `/tileMatrixSets`, or following links
- Should the TileSet conformance class require `.../tiles/{someId}` for the tileset?
- Should the TileSet conformance class require `.../{tmsId}/{tileMatrix}/{tileRow}/{tileCol}` for tiles? -- probably not to support the `.{extension}` approach, or allowing to set up _TileSets_ referencing tiles on e.g. a static service
- Should the _GeoData_ and _DataSet Tile Sets_ require fixed paths for dataset/collection vector tiles and map tiles?

**Comment by joanma747** [comment]
The current situation is:
* You can use the OpenAPI to find the "tileset path". You are expected to read links that have the templates.
* In OpenAPI a generic path for tiles is only possible in limited circumstances so we have to be sure that no requirement forces to have it. And even in this circumtacences you will not know the values of {tileMatrixSetId}.
  * Actually {tileMatrixSetId} is not required by the standard (there is only a permission that mentions it as a possibility).

**Comment by joanma747** [comment]
> {tileMatrixSetId} is currently an optional variable (permission)
yes

> The TileMatrixSet IDs is optional -- should OGC API - Tiles make it required?
no

> Clients [using the API approach only] have no ways of knowing valid values for the {tileMatrixSetId}, as IDs are not even required, so the API approach is limited
If all collections share the same TileMatrixSet's then the API definition (e.g.OpenAPI) could provide and enumeration for the {tileMatrixSetId} values.

> Even if ids were required, retrieving valid IDs would either require a /tileMatrixSets, or following links
Yes.

> Should the TileSet conformance class require .../tiles/{someId} for the tileset?
Today, what is normative is from collection to list of tilesets: rel: .../tilesets-map, rel: .../tilesets-vector, rel: .../tilesets-coverage.

Since there is no fix path, the OpenAPI document lists operations (path+httpMethod) that are not connected to the requirements in Standard. To fix this we could use the operationId defined by OpenAPI. This operationId are unique among the API description. We can propose to divide the operationId in two parts. The first part will be particular of the operation while the second part will point to the requirements class in the standard. E.g.
Buldings.getTileset-set
Buldings.getTileset
Buldings.getTile

We propose to add this as a *requirement* to the OpenAPI conformance class that does not exist yet.

> Should the TileSet conformance class require .../{tmsId}/{tileMatrix}/{tileRow}/{tileCol} for tiles? -- probably not to support the .{extension} approach, or allowing to set up TileSets referencing tiles on e.g. a static service
No. The order ins not specified and you need a URI template.

> Should the GeoData and DataSet Tile Sets require fixed paths for dataset/collection vector tiles and map tiles?
No

ACTION:
Create an OpenAPI requirements class with operationId.

**Comment by jerstlouis** [comment]
Today we seemed to be saying based on _[Requirement 11](http://docs.ogc.org/DRAFTS/20-057.html#_response_6)_ that a path ending with `.../tiles` is required for the TileSets-List conformance class.

Is that the case? That is different from the clarification above about "_what is normative..._"

The text [right above](http://docs.ogc.org/DRAFTS/20-057.html#_tilesets_path) also says:

> This class does not specify the path to a tileSet list. Refer to the Requirement Class "Dataset Tile Sets" and Requirement Class "Geo Data Resource TileSets" classes that describes two complementary mechanisms to associate tileSets to datasets and to geospatial data resources respectively.

so perhaps we really should remove the fixed path from 11 A?

**Comment by joanma747** [comment]
The operationId suffixes have been added. Is there anything else needed?

**Comment by jerstlouis** [comment]
@joanma747 Yes see [comment above](https://github.com/opengeospatial/ogcapi-tiles/issues/101#issuecomment-979375945)

**Comment by joanma747** [comment]
We reviewed the tilesets list requirement to be sure that the tileset path is completely flexible.
