### ISSUE TITLE
Do we need JSON and HTML conformance classes?

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-tiles#105]
_Processes_ for example have a _Processes_-specific JSON conformance class, in addition to the one defined in common.

A JSON conformance class would specify e.g. that the JSON encoding of the TileSetMetdata from 2DTMS should be used for an invidivudal tileset, and the JSON encoding for a list of tilesets.

Maybe we do not need separate ones for `tilesets-list` and `tileset`, and conformance to json implies that JSON is implemented for all other Tiles conformance classes?

Or does conformance to `tileset` and `tilesets-list` requires that JSON be implemented at minimum, and a JSON conformance class is not required?

**Comment by joanma747** [comment]
The proposal is:
* There is no need for HTML because it is in common
* We do not need a requirement for JSON because tilesets already states what need to be done for JSON. We will add a reference to JSON in tileset-list.
* We will create a new req. class for OpenAPI 3.0 with a mechanism for operationId's (see #104)

**Comment by joanma747** [comment]
After adding the JSON sub-requirement, this issue is done.
