### ISSUE TITLE
Examples 1 and 2 of the tileMatrixSet schema in Clause 8.3.2 need to be updated

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-tiles#140]
Examples 1 and 2 of the tileMatrixSet schema need to be updated to match the schemas.opengis.net

Verified by @jerstlouis that [tileMatrixSet.yaml at schemas.opengis.net](https://schemas.opengis.net/ogcapi/tiles/part1/1.0/openapi/schemas/tms/tileMatrixSet.yaml) is up to date.

**Comment by ghobona** [comment]
This issue is more about Example 2.

See attached.

<img width="1136" alt="Screenshot 2022-11-30 at 11 09 43" src="https://user-images.githubusercontent.com/18121038/204768543-5b8319b1-f788-4de2-8fdd-d6182bc6d1ed.png">

**Comment by cportele** [comment]
But the Tile Matrix Sets resource does not contain the Tile Matrix Set resources themselves, but a list of them with basic information (id, link, title, canonical URI). I think the standard is correct.

Well, with the exception that the schemas are shown as "examples", but this is probably a Metanorma issue?

**Comment by jerstlouis** [comment]
@cportele This particular schema is about the tile matrix set definition , it is for the recommendation (not requirement) for definitions at `/tileMatrixSets/{tileMatrixSetId}`.
So in this case it is the [tileMatrixSet](https://schemas.opengis.net/tms/2.0/json/tileMatrixSet.json) schema which correctly uses simply `uri` (because it is the URI for itself). The example below it correctly uses URI.

It is just that embedded schema in the spec which was not updated after a mistake was corrected.
It is correct in both the tiles OpenAPI examples and in the 2DTMS schemas.

**Comment by joanma747** [comment]
First: The "example 2" says: "id-link from OGC API - Common". I have not been able to find it in any of the API common materials. So this reference to "commons" should be removed. So I'm now in the assumption that this schema is "API tiles specific".

Secondly: The property is called "tileMatrixSetURI" because it want to be consistent with the 2dTMS metadata where this file:
.../tms/2.0/json/tileSet.json"

says:

```
"tileMatrixSetURI":
		{
			"description": "Reference to a Tile Matrix Set on an official source for Tile Matrix Sets such as the OGC-NA definition server (http://www.opengis.net/def/tms). Required if the tile matrix set is registered on an open official source.",
			"type": "string",
			"format": "uri"
		},

```
The intention is to reference an official source of TileMatrixSets.

**Comment by jerstlouis** [comment]
@joanma747 I believe this reference to _OGC API - Common_ was a "Replace All" that went wrong, where it was said originally was simply "Common tilematrixset".
