### ISSUE TITLE
TMS definition on Tileset Requirements Class 2

### ISSUE THREAD

**Issue by doublebyte1** [opengeospatial/ogcapi-tiles#164]
[Requirements class 2 establishes the following essential elements](https://docs.ogc.org/is/20-057/20-057.html#toc30):

- A link to the definition of the TileMatrixSet (either one registered in the [OGC TileMatrixSet register](https://defs.opengis.net/vocprez/object?uri=http%3A//www.opengis.net/def/tms) that is controlled by the [OGC Naming Authority (OGC-NA)](https://www.ogc.org/standards/na) SubCommittee (SC), or to a custom TileMatrixSet definition).
- A TileMatrixSet URI in the case of a TileMatrixSet registered with an authority (e.g. the OGC TileMatrixSet register).
- A Coordinate Reference System (usually provided as a URI).
- A templated link (URI) to individual tiles.
- A data type (indicating whether the tileset consists of vector, coverage or map tiles).

If a server uses a well-known TMS, is it acceptable to link to one of the definitions on Annex D of OGC 2D TMS?
https://docs.ogc.org/is/17-083r4/17-083r4.html#toc48

**Comment by jerstlouis** [comment]
@doublebyte1 The definition link needs to be retrievable as `application/json` following the JSON schema defined in 2DTMS (it cannot just point to an HTML or PDF document).

It also should not point to https://schemas.opengis.net/tms/2.0/json/examples/tilematrixset/ because these are _examples_.

It should not point to the 2DTMS repository hosted on GitHub either (e.g., https://raw.githubusercontent.com/opengeospatial/2D-Tile-Matrix-Set/master/registry/json/WorldCRS84Quad.json) because unfortunately, it does not support returning a proper `application/json` Content-Type: response header:

```
curl -H "Accept: application/json" -v https://raw.githubusercontent.com/opengeospatial/2D-Tile-Matrix-Set/master/registry/json/WorldCRS84Quad.json
```

Ideally, the link should be from the server itself so as not to rely on a third-party.

As a second best choice, the link should be to a definition provided by the OGC definition server, if the definition server was able to acommodate this need. Unfortunately, the OGC definition server is **still not capable of serving this purpose**, as discussed in https://github.com/opengeospatial/NamingAuthority/issues/198 .

For these reasons, servers really should provide their own definitions until the OGC Definition Server is fixed to support this capability.

**Comment by doublebyte1** [comment]
@jerstlouis understood, thank you!
