### ISSUE TITLE
New proposed structure for OGC API tiles

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/ogcapi-tiles#41]
1.1. TileSet - single tile set (what's at /tiles/{TileMatrixSetId}, no fixed path) + Annex 2 (osm + tilejson)
1.2. TileSets - Multiple tile sets (what's at /tiles, no fixed path) 
1.3. DatasetTileSets - OGC API Common - Part 1 (dataset, /tiles resource at the root) 
1.4. GeoDataResourceSelection - together with 3, collections= query parameters
1.5. GeoDataResourceTileSets - OGC API Common - Part 2 / OGC Feature - Part 1 (collection connection, /tiles resource after {collectionID})

2.1. TMS description - How to use a full TMS description that is not one of the Annex D, E and H, in 2D-TMS

**Comment by jerstlouis** [comment]
1.1 example: http://maps.ecere.com/geoapi/collections/vtp/Daraa2/tiles/WebMercatorQuad?f=json
1.2 example: http://maps.ecere.com/geoapi/collections/vtp/Daraa2/tiles?f=json

Since no paths are fixed, if we stick to this current approach of 1.1 being just a restricted version of 1.2 with a single TileSet, then perhaps 1.1 and 1.2 should be a single conformance class expressed as having 1 or more TileSet (and some representation like tileJSON might have an inherent limitation of a single TileSet).

Alternatively, perhaps 1.2 could simply list the tile sets and link to the 1.1 TileSet resources, each with a single TileMatrixSetLink. This would not be directly compatible with existing implementations, and forces an extra resource request roundtrip, but perhaps still worthwhile to consider.

**Comment by joanma747** [comment]
1.1. TileSet - single tile set (what's at /tiles/{TileMatrixSetId}, no fixed path) + Annex 2 (osm + tilejson)
Defines the response of a TileSet GET request (but not the path or the link for the request). 
The response has two formats: tilejson and OGC json. The OGC json includes tilematrixset links, a central point (optional), a links to the URI template to individual tiles, and the geospatial data resources involved in the creation of the tiles (optional).
Defines how to formulate a request for individual tiles and how the response will look like (success and failure)

1.2. TileSets - Multiple tile sets (what's at /tiles, no fixed path)
Defines the response of a TileSets GET request that includes a link to the tileset or an array for tileset responses. It defines the paths to the tileset resources.

1.3. DatasetTileSets - OGC API Common - Part 1 (dataset, /tiles resource at the root)
Defines how to get tiles from the dataset (or datasets) represented by the services. it will tell the path to get a tilesets resources

1.4. GeoDataResourceSelection - together with 3, collections= query parameters
It will define how to include a query parameter to subsets of the dataset (e.g. which geospatial data resources are involved in the creation tiles.

1.5. GeoDataResourceTileSets - OGC API Common - Part 2 / OGC Feature - Part 1 (collection connection, /tiles resource after {collectionID})
It will define how to specify the a link to tilesets containing a representation of this geo data resource (path).


2.1. TMS description - How to use a full TMS description that is not one of the Annex D, E and H, in 2D-TMS

**Comment by joanma747** [comment]
See the restructure of the classes for OGC API tiles and OGC API maps in https://github.com/opengeospatial/OGC-API-Maps/issues/32

**Comment by jerstlouis** [comment]
Note that this has been applied for a while and further cleaned up.
https://github.com/opengeospatial/ogcapi-tiles/pull/70 further splits _Tileset_ into:
- _Core_: tiles available from a any URL that can be composed using any 3 variables representing TMS matrix, row, column
- _Tileset_: tileset metadata including template defined with {tileMatrix}, {tileRow} and {tileCol}

**Comment by joanma747** [comment]
I believe we can close this issseu
