### ISSUE TITLE
render order of resources specified by geodata parameter

### ISSUE THREAD

**Issue by pomakis** [opengeospatial/ogcapi-tiles#49]
The render order of the resources specified by "geodata" parameter should be explicitly defined.  There are two reasonable options:

1) Allow the server to decide which render order is most appropriate.  This is the behaviour when the "geodata" parameter is absent, but doesn't give the client the ability to reorder layers.

2) Require the server to render the collections in the order specified.  This is the behaviour of a WMS GetMap request.  The WMS 1.3.0 specification (OGC 06-042), section 7.3.3.3, states the following: "A WMS shall render the requested layers by drawing the leftmost in the list bottommost, the next one over that, and so on.".

**Comment by mcechini** [comment]
I'm in favor of enforcing a similar "leftmost == bottommost" order.  That way there aren't any surprises for the client

**Comment by jerstlouis** [comment]
While I agree with leftmost == bottommost in general, when a style is used, our CMSS styling language has an explicit `zOrder` property which if specified overrides layer ordering, so that requirement would be problematic. The featurs of multiple layers can even be intertwined if the zOrdering is based on feature properties (e.g. we use this in our OpenStreetMap styling rules). So I am against that being requirement; it could be a recommendation.

**Comment by mcechini** [comment]
So, perhaps the "default behavior" would be leftmost == bottommost?  And if a server wants to override that with a custom styling language, they are free to do so.

Inherent here is that there wouldn't be anything in the WMS specification/response that explicitly says "leftmost == bottommost". So no `order="default"` attribute.  Instead a client would have to read your documentation to know that you are offering alternative behavior.  Yes?

**Comment by jerstlouis** [comment]
@mcechini Yes well I think it would not be possible to state this in a requirement while supporting the use case of intertwined layers based on styling rule.

A recommendation could say something like "Layers should be ordered from bottom to top following the left to right order of the specifiedgeodata , unless the ordering is controlled by another mechanism (e.g. such as portrayal rules for a selected style).

**Comment by pomakis** [comment]
One problem with making this a recommendation and not a requirement is that a client application that wishes to provide layer-reordering controls would have no choice but to make a separate HTTP request for each layer, regardless of the server it's talking to.  Even if 90% of the server implementations support client-supplied ordering, the client won't be able to rely on that capability.  Which is unfortunate, because it's the behaviour that's been expected of WMS servers for the last 20 years.  That being said, perhaps it isn't so bad, because most client applications probably make a separate HTTP request for each layer anyways (especially if the layers are from multiple servers).

**Comment by mcechini** [comment]
Well, if the client is interacting with multiple WMS servers... then it is probably not utilizing a specific server's "another mechanism (e.g. such as portrayal rules for a selected style)" ... therefore it would not be providing the information necessary in order to take advantage of that alternative ordering.  And thus, the expectation is that the server would be honoring the left=bottom order.  

So, Jerome's recommendation above could be modified to state that the "default behavior is to order left=bottom unless..."

**Comment by jerstlouis** [comment]
@mcechini note that in OGC API - Maps core it is the sevcer that is providing the style (though users could potentially use OGC API - Styles to modify and upload new styles), so this could always happen as part of a style being in use.

**Comment by joanma747** [comment]
Solution decided in 2020-10-29 telco.

What does not reflect the order:
The orderr of the collections in /collections seems not important in this decision.
The order could be declared in the tileset metadata is not relevant.

What does reflect the order:
First, the style can control the order (if the encoding allows for that)
Secondly ,if there is a collections= and the styles does not overwrite the order the "leftmost = bottommost" rule applies.

**Comment by joanma747** [comment]
Solution applied in requirement https://github.com/opengeospatial/ogcapi-tiles/blob/master/core/standard/requirements/collections-selection/REQ_query-collections.adoc

**Comment by joanma747** [comment]
We accepted the change in 9-9-2021.
