### ISSUE TITLE
Resources and common direct links in overview is confusing

### ISSUE THREAD

**Issue by cholmes** [opengeospatial/ogcapi-tiles#8]
The table 1 on https://github.com/opengeospatial/OGC-API-Tiles/blob/master/standard/clause_6_overview.adoc#how-to-approach-an-ogc-api has me pretty confused. 

I'm not sure about if the 'map' URL's here are just remants of the split in repos, and this should just have the tiles stuff?

But then if it's just tiles I'm confused because they all say 'vector tiles' - can those endpoints return raster tiles? 

In relation to #7 I think we should just have the 'core' pieces in this overview, and then could have an 'extension overview' in the extensions folder, that shows all the possible endpoints.

**Comment by ghobona** [comment]
@cholmes I could not find the table you were referring to. I think it has been removed. 

Could you please confirm that that is the case?

https://htmlpreview.github.io/?https://github.com/opengeospatial/OGC-API-Tiles/blob/master/core/standard/OAPI_Tiles.html

If it has been removed, we can close this issue.

**Comment by ghobona** [comment]
Discussion on 2020-07-30 SWG call.

On table 1:

* We could replace 'vector tiles' with 'tiled data'
* Alternatively, simply refer to just 'tiles'

**Comment by jerstlouis** [comment]
A related discussion is whether a stand-alone Tiles API could be possible, which could list all available tilesets regarding of whether they area data tile (e.g. vector features or coverage) or rendered map tiles. That is proposed in issue https://github.com/opengeospatial/OGC-API-Tiles/issues/6 .

In https://github.com/opengeospatial/OGC-API-Tiles/issues/43, I propose that a base Tilesets-List conformance class lists all tilesets and qualify each tile set with a TMS and a `dataType`. `/tiles` could implement that, whether it is at `{datasetAPI}/tiles` for Dataset-TileSet C.C., or at `{collectionId}/tiles` for Geodata-TileSet C.C.

OGC API - Maps Part 1: Core can also describe a simple conformance class Maps-Tiles which requires that Maps tilesets (with a dependency on OGC API - Tiles - Part 1's Tilesets-List C.C.) are available at both `{collectionId}/tiles` (along with other kind of tiles) as well as at `{collectionId}/map/{styleId}/tiles` (only map tiles for that specific style).

**Comment by mcechini** [comment]
+1 on replacing "vector tiles".  I know of nothing in this specification that is specific to vector tiles.  Maybe that's what folks are implementing first, but the specification is format agnostic... and I think it could be confusing to have the very first table of this document give the perception that scope is limited to vector tiles. 

"tiled data" is problematic because raster imagery is not necessarily data... though still better than "vector tiles" IMO.  Just "tiles" seems fine

**Comment by mcechini** [comment]
I also echo Chris' question about whether all of the /map reference should remain. Though I suppose those that ultimately end up in a tile should stay, since this is the tiles spec.  Then perhaps the standalone /map resources are included just for context

For example: /map/tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}

**Comment by mcechini** [comment]
And responding to Gobe's comment above... presumably I (as an implementer) could expose the same tiles through the following two endpoints.  I suppose if having a specific _Maps-Tiles_ conformance class made it easier for a client to know that the server was "double exposing" the resources... then sure.

/collections/{collectionId}/tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}
/collections/{collectionId}/map/{styleId}/tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}

**Comment by joanma747** [comment]
Note that now the consensus about paths is:
~~/collections/{collectionId}/map/{styleId}/tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}~~
/collections/{collectionId}/{styleId}/map/tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}

**Comment by joanma747** [comment]
Can we consider this issue closed?

**Comment by jerstlouis** [comment]
SWG 2021-08-12: Table 8 now in the overview could still be improved.
Headers (Tiles, Maps, Map Tiles) could use some formatting to distinguish them from content within.
The paths above could also be regrouped under a header as well?
"Vector Tiles description" seems wrong since this is the list of TileSets for vector tiles for a particular collection.
And below "Vector Tiles description (geospatial resources)" is the list of TileSets for (possibly vector tiles for the whole dataset.
"Vector Tile" with same path is there twice.

"description" in general could say "tileset metadata" to be clearer
The same "description" text is used for the "list of tilesets" which could also be clearer.
There are paths to individual map tiles for a particular style, but not for the default map tiles.

**Comment by joanma747** [comment]
Yet another issue related to https://github.com/opengeospatial/ogcapi-tiles/issues/54 and https://github.com/opengeospatial/ogcapi-tiles/issues/56

**Comment by joanma747** [comment]
Some solutions applied to the recommendations on table 8 from @jerstlouis last comment

**Comment by joanma747** [comment]
Accepted in the OGC tiles SWG telco today
