### ISSUE TITLE
Overview of the "tiles core" mentions \tileMatrixSets but definition is missing

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/ogcapi-tiles#87]
At some point in history, we decided that "\tileMatrixSets" (enumerations of tileMatrixSets) should be defined in the core (also named TMXS in some diagrams). The overview of the document reflects this position.  However there is no conformance class defining this path in the document.

We should add this in the core document as agreed.

There is a "project" for a part TMXS that should be removed: https://github.com/opengeospatial/ogcapi-tiles/projects/3

**Comment by joanma747** [comment]
TMXS has been added to the core document.

**Comment by jerstlouis** [comment]
While enumerating the list of supported tile matrix set is useful, especially if the server supports the same tile matrix sets for all collections, as far as the API and clients are concerned the  tilesets will provide a `tileMatrixSetDefinition` which could potentially link to either such resources, or somewhere else where the definition is provided.

I believe recently we decided that either `tileMatrixSetDefinition` or `tileMatrixSet` would be required, so that even Well-Known TileMatrixSets would have a definition (which could point to the official OGC definition in JSON).

In light of this, is it necessary to have that conformance class? It seems that it would only be a convenience for users to explore, but not something clients would make use of since the proper approach for clients would be to follow the `tileMatrixSetDefinition` property link (this makes me wonder, should `tileMatrixSetDefinition` be a link relation type and this be in the `links` of the tileset instead?). Requirements and conformance classes for `/tileMatrixSets` may potentially confuse client developers. A recommendation to list tile matrix sets there if they apply to all collections however would be great.

Thoughts welcome.

**Comment by joanma747** [comment]
Conformance class for \tileMatrixSets could be useful for managing TileMatrixSets that are not common and could be created or updated in the service API. Currently that we are only defining the "GET" requests, and witht he introduction of the TileSetMetadata, there is no need to specify a Conformance class for \tileMatrixSets. 

As a consequence, the recommendation \core\standard\recommendations/tileset/REC_tmxslink.adoc[] in \core\standard\clause_7_tile_tileSet.adoc has been extended to cover this and there is a new section supporting the recommendation without any requirement.

**Comment by joanma747** [comment]
Decided to close on 9-9-2021 meeting
